name: CI
on: [ push ]
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, name: "Ubuntu" }
          - { os: macos-latest, name: "Mac" }
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.name }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make -j$(nproc) test
      - run: make -j$(nproc) release
      - run: make -j$(nproc) perft
